services:
  apps:
    build: ./apps
    container_name: ct-apps-jundi
    image: jdayrf/apps-jundi
    restart: always
    ports:
      - "5000:3000"
    volumes:
      - apps-data:/app/public/images

volumes:
  apps-data: